# SPDX-FileCopyrightText: 2017-2022 Blender Foundation
#
# SPDX-License-Identifier: GPL-2.0-or-later
# HLL preset, generated by tools/make_hll_presets.py from the
# 'Animals/horse' stock metarig — do not hand-edit.
# Quadruped starting point (stalker-scale creature).

import bpy
from mathutils import Color


def create(obj):
    # generated by rigforge.utils.write_metarig
    bpy.ops.object.mode_set(mode="EDIT")
    arm = obj.data

    for _ in range(6):
        arm.rigforge_colors.add()

    arm.rigforge_colors[0].name = "Root"
    arm.rigforge_colors[0].active = Color((0.5490, 1.0000, 1.0000))
    arm.rigforge_colors[0].normal = Color((0.4353, 0.1843, 0.4157))
    arm.rigforge_colors[0].select = Color((0.3140, 0.7840, 1.0000))
    arm.rigforge_colors[0].standard_colors_lock = True
    arm.rigforge_colors[1].name = "IK"
    arm.rigforge_colors[1].active = Color((0.5490, 1.0000, 1.0000))
    arm.rigforge_colors[1].normal = Color((0.6039, 0.0000, 0.0000))
    arm.rigforge_colors[1].select = Color((0.3140, 0.7840, 1.0000))
    arm.rigforge_colors[1].standard_colors_lock = True
    arm.rigforge_colors[2].name = "Special"
    arm.rigforge_colors[2].active = Color((0.5490, 1.0000, 1.0000))
    arm.rigforge_colors[2].normal = Color((0.9569, 0.7882, 0.0471))
    arm.rigforge_colors[2].select = Color((0.3140, 0.7840, 1.0000))
    arm.rigforge_colors[2].standard_colors_lock = True
    arm.rigforge_colors[3].name = "Tweak"
    arm.rigforge_colors[3].active = Color((0.5490, 1.0000, 1.0000))
    arm.rigforge_colors[3].normal = Color((0.0392, 0.2118, 0.5804))
    arm.rigforge_colors[3].select = Color((0.3140, 0.7840, 1.0000))
    arm.rigforge_colors[3].standard_colors_lock = True
    arm.rigforge_colors[4].name = "FK"
    arm.rigforge_colors[4].active = Color((0.5490, 1.0000, 1.0000))
    arm.rigforge_colors[4].normal = Color((0.1176, 0.5686, 0.0353))
    arm.rigforge_colors[4].select = Color((0.3140, 0.7840, 1.0000))
    arm.rigforge_colors[4].standard_colors_lock = True
    arm.rigforge_colors[5].name = "Extra"
    arm.rigforge_colors[5].active = Color((0.5490, 1.0000, 1.0000))
    arm.rigforge_colors[5].normal = Color((0.9686, 0.2510, 0.0941))
    arm.rigforge_colors[5].select = Color((0.3140, 0.7840, 1.0000))
    arm.rigforge_colors[5].standard_colors_lock = True

    bone_collections = {}

    for bcoll in list(arm.collections_all):
        arm.collections.remove(bcoll)

    def add_bone_collection(
        name, *, parent=None, ui_row=0, ui_title="", sel_set=False, color_set_id=0
    ):
        new_bcoll = arm.collections.new(name, parent=bone_collections.get(parent))
        new_bcoll.rigforge_ui_row = ui_row
        new_bcoll.rigforge_ui_title = ui_title
        new_bcoll.rigforge_sel_set = sel_set
        new_bcoll.rigforge_color_set_id = color_set_id
        bone_collections[name] = new_bcoll

    def assign_bone_collections(pose_bone, *coll_names):
        assert not len(pose_bone.bone.collections)
        for name in coll_names:
            bone_collections[name].assign(pose_bone)

    def assign_bone_collection_refs(params, attr_name, *coll_names):
        ref_list = getattr(params, attr_name + "_coll_refs", None)
        if ref_list is not None:
            for name in coll_names:
                ref_list.add().set_collection(bone_collections[name])

    add_bone_collection("Face", ui_row=1, color_set_id=5)
    add_bone_collection(
        "Face (Primary)", ui_row=2, ui_title="(Primary)", color_set_id=4
    )
    add_bone_collection("Spine", ui_row=4, color_set_id=3)
    add_bone_collection("Spine (Tweak)", ui_row=5, ui_title="(Tweak)", color_set_id=4)
    add_bone_collection("Arm.L (IK)", ui_row=7, color_set_id=2)
    add_bone_collection("Arm.L (FK)", ui_row=8, ui_title="(FK)", color_set_id=5)
    add_bone_collection("Arm.L (Tweak)", ui_row=9, ui_title="(Tweak)", color_set_id=4)
    add_bone_collection("Arm.R (IK)", ui_row=7, color_set_id=2)
    add_bone_collection("Arm.R (FK)", ui_row=8, ui_title="(FK)", color_set_id=5)
    add_bone_collection("Arm.R (Tweak)", ui_row=9, ui_title="(Tweak)", color_set_id=4)
    add_bone_collection("Leg.L (IK)", ui_row=11, color_set_id=2)
    add_bone_collection("Leg.L (FK)", ui_row=12, ui_title="(FK)", color_set_id=5)
    add_bone_collection("Leg.L (Tweak)", ui_row=13, ui_title="(Tweak)", color_set_id=4)
    add_bone_collection("Leg.R (IK)", ui_row=11, color_set_id=2)
    add_bone_collection("Leg.R (FK)", ui_row=12, ui_title="(FK)", color_set_id=5)
    add_bone_collection("Leg.R (Tweak)", ui_row=13, ui_title="(Tweak)", color_set_id=4)
    add_bone_collection("Tail", ui_row=15, color_set_id=6)
    add_bone_collection("Hair", ui_row=2, color_set_id=6)
    add_bone_collection("Root", ui_row=18, color_set_id=1)

    bones = {}

    bone = arm.edit_bones.new("spine.001")
    bone.head = -0.0000, -0.6044, 1.0462
    bone.tail = -0.0000, -0.2954, 1.0462
    bone.roll = 0.0000
    bone.use_connect = False
    bones["spine.001"] = bone.name
    bone = arm.edit_bones.new("tail.001")
    bone.head = -0.0000, -0.6727, 1.0895
    bone.tail = -0.0000, -0.7525, 1.0815
    bone.roll = -3.1416
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones["spine.001"]]
    bones["tail.001"] = bone.name
    bone = arm.edit_bones.new("spine.002")
    bone.head = -0.0000, -0.2954, 1.0462
    bone.tail = -0.0000, -0.1566, 0.9952
    bone.roll = -3.1416
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones["spine.001"]]
    bones["spine.002"] = bone.name
    bone = arm.edit_bones.new("tail.002")
    bone.head = -0.0000, -0.7525, 1.0815
    bone.tail = -0.0000, -0.8567, 0.9846
    bone.roll = -3.1416
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones["tail.001"]]
    bones["tail.002"] = bone.name
    bone = arm.edit_bones.new("spine.003")
    bone.head = -0.0000, -0.1566, 0.9952
    bone.tail = -0.0000, -0.0221, 0.9643
    bone.roll = -3.1416
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones["spine.002"]]
    bones["spine.003"] = bone.name
    bone = arm.edit_bones.new("pelvis.R")
    bone.head = -0.0000, -0.6044, 1.0462
    bone.tail = -0.1352, -0.3313, 1.1837
    bone.roll = 2.2177
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones["spine.002"]]
    bones["pelvis.R"] = bone.name
    bone = arm.edit_bones.new("pelvis.L")
    bone.head = -0.0000, -0.6044, 1.0462
    bone.tail = 0.1352, -0.3313, 1.1837
    bone.roll = -2.2177
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones["spine.002"]]
    bones["pelvis.L"] = bone.name
    bone = arm.edit_bones.new("hip")
    bone.head = -0.0000, -0.6044, 1.0462
    bone.tail = -0.0000, -0.3477, 0.7659
    bone.roll = -3.1416
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones["spine.002"]]
    bones["hip"] = bone.name
    bone = arm.edit_bones.new("tail.003")
    bone.head = -0.0000, -0.8567, 0.9846
    bone.tail = -0.0000, -1.0334, 0.8692
    bone.roll = -3.1416
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones["tail.002"]]
    bones["tail.003"] = bone.name
    bone = arm.edit_bones.new("spine.004")
    bone.head = -0.0000, -0.0221, 0.9643
    bone.tail = 0.0000, 0.1327, 0.9551
    bone.roll = -3.1416
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones["spine.003"]]
    bones["spine.004"] = bone.name
    bone = arm.edit_bones.new("abdomen")
    bone.head = -0.0000, -0.1127, 0.9155
    bone.tail = -0.0000, -0.1531, 0.6759
    bone.roll = -3.1416
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones["spine.003"]]
    bones["abdomen"] = bone.name
    bone = arm.edit_bones.new("thigh.R")
    bone.head = -0.3000, -0.5500, 1.0568
    bone.tail = -0.3008, -0.4995, 0.7751
    bone.roll = -0.1659
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones["pelvis.R"]]
    bones["thigh.R"] = bone.name
    bone = arm.edit_bones.new("thigh.L")
    bone.head = 0.3000, -0.5500, 1.0568
    bone.tail = 0.3008, -0.4995, 0.7751
    bone.roll = 0.1659
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones["pelvis.L"]]
    bones["thigh.L"] = bone.name
    bone = arm.edit_bones.new("tail.004")
    bone.head = -0.0000, -1.0334, 0.8692
    bone.tail = -0.0000, -1.1816, 0.8316
    bone.roll = -3.1416
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones["tail.003"]]
    bones["tail.004"] = bone.name
    bone = arm.edit_bones.new("spine.005")
    bone.head = 0.0000, 0.1327, 0.9551
    bone.tail = 0.0000, 0.2756, 0.9606
    bone.roll = -3.1416
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones["spine.004"]]
    bones["spine.005"] = bone.name
    bone = arm.edit_bones.new("lower_leg.R")
    bone.head = -0.3008, -0.4995, 0.7751
    bone.tail = -0.3008, -0.6544, 0.4556
    bone.roll = -0.1667
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones["thigh.R"]]
    bones["lower_leg.R"] = bone.name
    bone = arm.edit_bones.new("lower_leg.L")
    bone.head = 0.3008, -0.4995, 0.7751
    bone.tail = 0.3008, -0.6544, 0.4556
    bone.roll = 0.1667
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones["thigh.L"]]
    bones["lower_leg.L"] = bone.name
    bone = arm.edit_bones.new("tail.005")
    bone.head = -0.0000, -1.1816, 0.8316
    bone.tail = -0.0000, -1.3207, 0.8365
    bone.roll = 3.1416
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones["tail.004"]]
    bones["tail.005"] = bone.name
    bone = arm.edit_bones.new("spine.006")
    bone.head = 0.0000, 0.2756, 0.9606
    bone.tail = 0.0000, 0.5695, 1.0369
    bone.roll = -3.1416
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones["spine.005"]]
    bones["spine.006"] = bone.name
    bone = arm.edit_bones.new("shoulder.R")
    bone.head = -0.0702, 0.3776, 1.1837
    bone.tail = -0.1401, 0.5209, 0.8982
    bone.roll = -2.9733
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones["spine.005"]]
    bones["shoulder.R"] = bone.name
    bone = arm.edit_bones.new("breast.R")
    bone.head = -0.0679, 0.4156, 0.8198
    bone.tail = -0.0679, 0.6327, 0.7050
    bone.roll = -3.1416
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones["spine.005"]]
    bones["breast.R"] = bone.name
    bone = arm.edit_bones.new("shoulder.L")
    bone.head = 0.0702, 0.3776, 1.1837
    bone.tail = 0.1401, 0.5209, 0.8982
    bone.roll = 2.9733
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones["spine.005"]]
    bones["shoulder.L"] = bone.name
    bone = arm.edit_bones.new("breast.L")
    bone.head = 0.0679, 0.4156, 0.8198
    bone.tail = 0.0679, 0.6327, 0.7050
    bone.roll = -3.1416
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones["spine.005"]]
    bones["breast.L"] = bone.name
    bone = arm.edit_bones.new("chest")
    bone.head = 0.0000, 0.1635, 0.9130
    bone.tail = 0.0000, 0.1679, 0.6047
    bone.roll = -3.1416
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones["spine.005"]]
    bones["chest"] = bone.name
    bone = arm.edit_bones.new("hind_foot.R")
    bone.head = -0.3008, -0.6544, 0.4556
    bone.tail = -0.3008, -0.5993, 0.1508
    bone.roll = -0.1679
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones["lower_leg.R"]]
    bones["hind_foot.R"] = bone.name
    bone = arm.edit_bones.new("hind_foot.L")
    bone.head = 0.3008, -0.6544, 0.4556
    bone.tail = 0.3008, -0.5993, 0.1508
    bone.roll = 0.1679
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones["lower_leg.L"]]
    bones["hind_foot.L"] = bone.name
    bone = arm.edit_bones.new("neck.001")
    bone.head = 0.0000, 0.5695, 1.0369
    bone.tail = 0.0000, 0.6753, 1.1606
    bone.roll = 3.1416
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones["spine.006"]]
    bones["neck.001"] = bone.name
    bone = arm.edit_bones.new("mane_base.05")
    bone.head = 0.0000, 0.4590, 1.2666
    bone.tail = 0.0000, 0.4336, 1.3028
    bone.roll = 3.1416
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones["spine.006"]]
    bones["mane_base.05"] = bone.name
    bone = arm.edit_bones.new("upper_arm.R")
    bone.head = -0.3000, 0.5500, 0.8698
    bone.tail = -0.3000, 0.4320, 0.6309
    bone.roll = -0.1704
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones["shoulder.R"]]
    bones["upper_arm.R"] = bone.name
    bone = arm.edit_bones.new("upper_arm.L")
    bone.head = 0.3000, 0.5500, 0.8698
    bone.tail = 0.3000, 0.4320, 0.6309
    bone.roll = 0.1704
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones["shoulder.L"]]
    bones["upper_arm.L"] = bone.name
    bone = arm.edit_bones.new("r_toe.R")
    bone.head = -0.3008, -0.5993, 0.1508
    bone.tail = -0.3008, -0.5574, 0.0789
    bone.roll = -0.1661
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones["hind_foot.R"]]
    bones["r_toe.R"] = bone.name
    bone = arm.edit_bones.new("r_toe.L")
    bone.head = 0.3008, -0.5993, 0.1508
    bone.tail = 0.3008, -0.5574, 0.0789
    bone.roll = 0.1661
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones["hind_foot.L"]]
    bones["r_toe.L"] = bone.name
    bone = arm.edit_bones.new("neck.002")
    bone.head = 0.0000, 0.6753, 1.1606
    bone.tail = 0.0000, 0.7761, 1.2774
    bone.roll = -3.1416
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones["neck.001"]]
    bones["neck.002"] = bone.name
    bone = arm.edit_bones.new("mane_base.04")
    bone.head = 0.0000, 0.5914, 1.3207
    bone.tail = 0.0000, 0.5525, 1.3795
    bone.roll = 3.1416
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones["neck.001"]]
    bones["mane_base.04"] = bone.name
    bone = arm.edit_bones.new("mane_top.05")
    bone.head = 0.0000, 0.4336, 1.3028
    bone.tail = 0.0000, 0.4083, 1.3391
    bone.roll = 3.1416
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones["mane_base.05"]]
    bones["mane_top.05"] = bone.name
    bone = arm.edit_bones.new("forearm.R")
    bone.head = -0.3000, 0.4320, 0.6309
    bone.tail = -0.3000, 0.4368, 0.3605
    bone.roll = -0.1698
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones["upper_arm.R"]]
    bones["forearm.R"] = bone.name
    bone = arm.edit_bones.new("forearm.L")
    bone.head = 0.3000, 0.4320, 0.6309
    bone.tail = 0.3000, 0.4368, 0.3605
    bone.roll = 0.1698
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones["upper_arm.L"]]
    bones["forearm.L"] = bone.name
    bone = arm.edit_bones.new("r_hoof.R")
    bone.head = -0.3008, -0.5574, 0.0789
    bone.tail = -0.3008, -0.5255, 0.0005
    bone.roll = -0.1671
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones["r_toe.R"]]
    bones["r_hoof.R"] = bone.name
    bone = arm.edit_bones.new("r_hoof.L")
    bone.head = 0.3008, -0.5574, 0.0789
    bone.tail = 0.3008, -0.5255, 0.0005
    bone.roll = 0.1671
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones["r_toe.L"]]
    bones["r_hoof.L"] = bone.name
    bone = arm.edit_bones.new("neck.003")
    bone.head = 0.0000, 0.7761, 1.2774
    bone.tail = 0.0000, 0.8714, 1.3270
    bone.roll = -3.1416
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones["neck.002"]]
    bones["neck.003"] = bone.name
    bone = arm.edit_bones.new("mane_base.03")
    bone.head = 0.0000, 0.7220, 1.3885
    bone.tail = 0.0000, 0.6908, 1.4518
    bone.roll = 3.1416
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones["neck.002"]]
    bones["mane_base.03"] = bone.name
    bone = arm.edit_bones.new("mane_top.04")
    bone.head = 0.0000, 0.5525, 1.3795
    bone.tail = 0.0000, 0.5135, 1.4383
    bone.roll = 3.1416
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones["mane_base.04"]]
    bones["mane_top.04"] = bone.name
    bone = arm.edit_bones.new("forefoot.R")
    bone.head = -0.3000, 0.4368, 0.3605
    bone.tail = -0.3000, 0.4197, 0.1659
    bone.roll = -0.1698
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones["forearm.R"]]
    bones["forefoot.R"] = bone.name
    bone = arm.edit_bones.new("forefoot.L")
    bone.head = 0.3000, 0.4368, 0.3605
    bone.tail = 0.3000, 0.4197, 0.1659
    bone.roll = 0.1698
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones["forearm.L"]]
    bones["forefoot.L"] = bone.name
    bone = arm.edit_bones.new("neck.004")
    bone.head = 0.0000, 0.8714, 1.3270
    bone.tail = 0.0000, 0.9627, 1.3381
    bone.roll = -3.1416
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones["neck.003"]]
    bones["neck.004"] = bone.name
    bone = arm.edit_bones.new("mane_base.02")
    bone.head = 0.0000, 0.8578, 1.4343
    bone.tail = 0.0000, 0.8413, 1.5028
    bone.roll = 3.1416
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones["neck.003"]]
    bones["mane_base.02"] = bone.name
    bone = arm.edit_bones.new("mane_top.03")
    bone.head = 0.0000, 0.6908, 1.4518
    bone.tail = 0.0000, 0.6596, 1.5150
    bone.roll = 3.1416
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones["mane_base.03"]]
    bones["mane_top.03"] = bone.name
    bone = arm.edit_bones.new("f_toe.R")
    bone.head = -0.3000, 0.4197, 0.1659
    bone.tail = -0.3000, 0.4620, 0.0706
    bone.roll = -0.1702
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones["forefoot.R"]]
    bones["f_toe.R"] = bone.name
    bone = arm.edit_bones.new("f_toe.L")
    bone.head = 0.3000, 0.4197, 0.1659
    bone.tail = 0.3000, 0.4620, 0.0706
    bone.roll = 0.1702
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones["forefoot.L"]]
    bones["f_toe.L"] = bone.name
    bone = arm.edit_bones.new("head")
    bone.head = 0.0000, 0.9627, 1.3381
    bone.tail = 0.0000, 1.2311, 1.2803
    bone.roll = -3.1416
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones["neck.004"]]
    bones["head"] = bone.name
    bone = arm.edit_bones.new("mane_base.01")
    bone.head = 0.0000, 0.9805, 1.4509
    bone.tail = 0.0000, 0.9886, 1.5209
    bone.roll = -3.1416
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones["neck.004"]]
    bones["mane_base.01"] = bone.name
    bone = arm.edit_bones.new("mane_base.06")
    bone.head = 0.0000, 1.0588, 1.4388
    bone.tail = 0.0000, 1.0924, 1.4608
    bone.roll = -3.1416
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones["neck.004"]]
    bones["mane_base.06"] = bone.name
    bone = arm.edit_bones.new("mane_top.02")
    bone.head = 0.0000, 0.8413, 1.5028
    bone.tail = 0.0000, 0.8247, 1.5715
    bone.roll = 3.1416
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones["mane_base.02"]]
    bones["mane_top.02"] = bone.name
    bone = arm.edit_bones.new("f_hoof.R")
    bone.head = -0.3000, 0.4620, 0.0706
    bone.tail = -0.3000, 0.5116, 0.0005
    bone.roll = -0.1708
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones["f_toe.R"]]
    bones["f_hoof.R"] = bone.name
    bone = arm.edit_bones.new("f_hoof.L")
    bone.head = 0.3000, 0.4620, 0.0706
    bone.tail = 0.3000, 0.5116, 0.0005
    bone.roll = 0.1708
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones["f_toe.L"]]
    bones["f_hoof.L"] = bone.name
    bone = arm.edit_bones.new("skull")
    bone.head = 0.0000, 0.9760, 1.3713
    bone.tail = 0.0000, 1.2562, 0.9825
    bone.roll = -3.1416
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones["head"]]
    bones["skull"] = bone.name
    bone = arm.edit_bones.new("ear.R")
    bone.head = -0.0498, 1.0217, 1.3959
    bone.tail = -0.0792, 1.0589, 1.4653
    bone.roll = 3.0150
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones["head"]]
    bones["ear.R"] = bone.name
    bone = arm.edit_bones.new("ear.L")
    bone.head = 0.0498, 1.0217, 1.3959
    bone.tail = 0.0792, 1.0589, 1.4653
    bone.roll = -3.0150
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones["head"]]
    bones["ear.L"] = bone.name
    bone = arm.edit_bones.new("jaw")
    bone.head = 0.0000, 1.0130, 1.1864
    bone.tail = 0.0000, 1.1099, 1.0927
    bone.roll = -3.1416
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones["head"]]
    bones["jaw"] = bone.name
    bone = arm.edit_bones.new("eye.R")
    bone.head = -0.0741, 1.0947, 1.3013
    bone.tail = -0.1492, 1.1001, 1.3065
    bone.roll = 0.1375
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones["head"]]
    bones["eye.R"] = bone.name
    bone = arm.edit_bones.new("nose.R")
    bone.head = -0.0337, 1.2180, 1.0671
    bone.tail = -0.0779, 1.2460, 1.0702
    bone.roll = 0.1390
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones["head"]]
    bones["nose.R"] = bone.name
    bone = arm.edit_bones.new("eye.L")
    bone.head = 0.0741, 1.0947, 1.3013
    bone.tail = 0.1493, 1.1001, 1.3065
    bone.roll = -0.1375
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones["head"]]
    bones["eye.L"] = bone.name
    bone = arm.edit_bones.new("nose.L")
    bone.head = 0.0338, 1.2180, 1.0671
    bone.tail = 0.0779, 1.2460, 1.0702
    bone.roll = -0.1390
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones["head"]]
    bones["nose.L"] = bone.name
    bone = arm.edit_bones.new("mane_top.01")
    bone.head = 0.0000, 0.9886, 1.5209
    bone.tail = 0.0000, 0.9967, 1.5910
    bone.roll = 3.1416
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones["mane_base.01"]]
    bones["mane_top.01"] = bone.name
    bone = arm.edit_bones.new("mane_top.06")
    bone.head = 0.0000, 1.0924, 1.4608
    bone.tail = 0.0000, 1.1260, 1.4827
    bone.roll = -3.1416
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones["mane_base.06"]]
    bones["mane_top.06"] = bone.name
    bone = arm.edit_bones.new("skull.R")
    bone.head = 0.0000, 0.9760, 1.3713
    bone.tail = -0.1173, 1.0607, 1.1816
    bone.roll = -2.8037
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones["skull"]]
    bones["skull.R"] = bone.name
    bone = arm.edit_bones.new("skull.L")
    bone.head = 0.0000, 0.9760, 1.3713
    bone.tail = 0.1173, 1.0607, 1.1816
    bone.roll = 2.8037
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones["skull"]]
    bones["skull.L"] = bone.name
    bone = arm.edit_bones.new("ear.R.001")
    bone.head = -0.0792, 1.0589, 1.4653
    bone.tail = -0.1086, 1.0960, 1.5347
    bone.roll = 3.0150
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones["ear.R"]]
    bones["ear.R.001"] = bone.name
    bone = arm.edit_bones.new("ear.L.001")
    bone.head = 0.0792, 1.0589, 1.4653
    bone.tail = 0.1086, 1.0960, 1.5347
    bone.roll = -3.0150
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones["ear.L"]]
    bones["ear.L.001"] = bone.name
    bone = arm.edit_bones.new("jaw.001")
    bone.head = 0.0000, 1.1099, 1.0927
    bone.tail = 0.0000, 1.1699, 0.9907
    bone.roll = -3.1416
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones["jaw"]]
    bones["jaw.001"] = bone.name

    bpy.ops.object.mode_set(mode="OBJECT")
    pbone = obj.pose.bones[bones["spine.001"]]
    pbone.rigforge_type = "spines.basic_spine"
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Spine")
    try:
        pbone.rigforge_parameters.pivot_pos = 2
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigforge_parameters, "tweak", "Spine (Tweak)")
    assign_bone_collection_refs(pbone.rigforge_parameters, "fk", "Spine (Tweak)")
    pbone = obj.pose.bones[bones["tail.001"]]
    pbone.rigforge_type = "spines.basic_tail"
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Tail")
    try:
        pbone.rigforge_parameters.copy_rotation_axes = (True, False, True)
    except AttributeError:
        pass
    try:
        pbone.rigforge_parameters.connect_chain = False
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigforge_parameters, "tweak", "Spine (Tweak)")
    pbone = obj.pose.bones[bones["spine.002"]]
    pbone.rigforge_type = ""
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Spine")
    pbone = obj.pose.bones[bones["tail.002"]]
    pbone.rigforge_type = ""
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Tail")
    pbone = obj.pose.bones[bones["spine.003"]]
    pbone.rigforge_type = ""
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Spine")
    pbone = obj.pose.bones[bones["pelvis.R"]]
    pbone.rigforge_type = "basic.super_copy"
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Spine")
    try:
        pbone.rigforge_parameters.make_widget = False
    except AttributeError:
        pass
    try:
        pbone.rigforge_parameters.make_control = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones["pelvis.L"]]
    pbone.rigforge_type = "basic.super_copy"
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Spine")
    try:
        pbone.rigforge_parameters.make_widget = False
    except AttributeError:
        pass
    try:
        pbone.rigforge_parameters.make_control = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones["hip"]]
    pbone.rigforge_type = ""
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Spine")
    pbone = obj.pose.bones[bones["tail.003"]]
    pbone.rigforge_type = ""
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Tail")
    pbone = obj.pose.bones[bones["spine.004"]]
    pbone.rigforge_type = ""
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Spine")
    pbone = obj.pose.bones[bones["abdomen"]]
    pbone.rigforge_type = ""
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Spine (Tweak)")
    pbone = obj.pose.bones[bones["thigh.R"]]
    pbone.rigforge_type = "limbs.rear_paw"
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Leg.L (IK)")
    try:
        pbone.rigforge_parameters.segments = 2
    except AttributeError:
        pass
    try:
        pbone.rigforge_parameters.ik_local_location = False
    except AttributeError:
        pass
    try:
        pbone.rigforge_parameters.bbones = 10
    except AttributeError:
        pass
    try:
        pbone.rigforge_parameters.fk_layers_extra = True
    except AttributeError:
        pass
    try:
        pbone.rigforge_parameters.tweak_layers_extra = True
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigforge_parameters, "fk", "Leg.L (FK)")
    assign_bone_collection_refs(pbone.rigforge_parameters, "tweak", "Leg.L (Tweak)")
    pbone = obj.pose.bones[bones["thigh.L"]]
    pbone.rigforge_type = "limbs.rear_paw"
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Leg.R (IK)")
    try:
        pbone.rigforge_parameters.segments = 2
    except AttributeError:
        pass
    try:
        pbone.rigforge_parameters.ik_local_location = False
    except AttributeError:
        pass
    try:
        pbone.rigforge_parameters.bbones = 10
    except AttributeError:
        pass
    try:
        pbone.rigforge_parameters.fk_layers_extra = True
    except AttributeError:
        pass
    try:
        pbone.rigforge_parameters.tweak_layers_extra = True
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigforge_parameters, "fk", "Leg.R (FK)")
    assign_bone_collection_refs(pbone.rigforge_parameters, "tweak", "Leg.R (Tweak)")
    pbone = obj.pose.bones[bones["tail.004"]]
    pbone.rigforge_type = ""
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Tail")
    pbone = obj.pose.bones[bones["spine.005"]]
    pbone.rigforge_type = ""
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Spine")
    pbone = obj.pose.bones[bones["lower_leg.R"]]
    pbone.rigforge_type = ""
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Leg.L (IK)")
    pbone = obj.pose.bones[bones["lower_leg.L"]]
    pbone.rigforge_type = ""
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Leg.R (IK)")
    pbone = obj.pose.bones[bones["tail.005"]]
    pbone.rigforge_type = ""
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Tail")
    pbone = obj.pose.bones[bones["spine.006"]]
    pbone.rigforge_type = ""
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Spine")
    pbone = obj.pose.bones[bones["shoulder.R"]]
    pbone.rigforge_type = "basic.super_copy"
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Arm.L (IK)")
    try:
        pbone.rigforge_parameters.make_widget = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones["breast.R"]]
    pbone.rigforge_type = "basic.super_copy"
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Spine (Tweak)")
    pbone = obj.pose.bones[bones["shoulder.L"]]
    pbone.rigforge_type = "basic.super_copy"
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Arm.R (IK)")
    try:
        pbone.rigforge_parameters.make_widget = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones["breast.L"]]
    pbone.rigforge_type = "basic.super_copy"
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Spine (Tweak)")
    pbone = obj.pose.bones[bones["chest"]]
    pbone.rigforge_type = "basic.super_copy"
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Spine (Tweak)")
    pbone = obj.pose.bones[bones["hind_foot.R"]]
    pbone.rigforge_type = ""
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Leg.L (IK)")
    pbone = obj.pose.bones[bones["hind_foot.L"]]
    pbone.rigforge_type = ""
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Leg.R (IK)")
    pbone = obj.pose.bones[bones["neck.001"]]
    pbone.rigforge_type = "spines.super_head"
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Spine")
    try:
        pbone.rigforge_parameters.connect_chain = True
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigforge_parameters, "tweak", "Spine (Tweak)")
    pbone = obj.pose.bones[bones["mane_base.05"]]
    pbone.rigforge_type = "limbs.super_finger"
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Hair")
    try:
        pbone.rigforge_parameters.copy_rotation_axes = (True, False, True)
    except AttributeError:
        pass
    try:
        pbone.rigforge_parameters.primary_rotation_axis = "Z"
    except AttributeError:
        pass
    try:
        pbone.rigforge_parameters.tweak_layers_extra = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones["upper_arm.R"]]
    pbone.rigforge_type = "limbs.front_paw"
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Arm.L (IK)")
    try:
        pbone.rigforge_parameters.limb_type = "paw"
    except AttributeError:
        pass
    try:
        pbone.rigforge_parameters.ik_local_location = False
    except AttributeError:
        pass
    try:
        pbone.rigforge_parameters.front_paw_heel_influence = 0.6000000238418579
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigforge_parameters, "fk", "Arm.L (FK)")
    assign_bone_collection_refs(pbone.rigforge_parameters, "tweak", "Arm.L (Tweak)")
    pbone = obj.pose.bones[bones["upper_arm.L"]]
    pbone.rigforge_type = "limbs.front_paw"
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Arm.R (IK)")
    try:
        pbone.rigforge_parameters.limb_type = "paw"
    except AttributeError:
        pass
    try:
        pbone.rigforge_parameters.ik_local_location = False
    except AttributeError:
        pass
    try:
        pbone.rigforge_parameters.front_paw_heel_influence = 0.6000000238418579
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigforge_parameters, "fk", "Arm.R (FK)")
    assign_bone_collection_refs(pbone.rigforge_parameters, "tweak", "Arm.R (Tweak)")
    pbone = obj.pose.bones[bones["r_toe.R"]]
    pbone.rigforge_type = ""
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Leg.L (IK)")
    pbone = obj.pose.bones[bones["r_toe.L"]]
    pbone.rigforge_type = ""
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Leg.R (IK)")
    pbone = obj.pose.bones[bones["neck.002"]]
    pbone.rigforge_type = ""
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Spine")
    pbone = obj.pose.bones[bones["mane_base.04"]]
    pbone.rigforge_type = "limbs.super_finger"
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Hair")
    try:
        pbone.rigforge_parameters.copy_rotation_axes = (True, False, True)
    except AttributeError:
        pass
    try:
        pbone.rigforge_parameters.primary_rotation_axis = "Z"
    except AttributeError:
        pass
    try:
        pbone.rigforge_parameters.tweak_layers_extra = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones["mane_top.05"]]
    pbone.rigforge_type = ""
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Hair")
    pbone = obj.pose.bones[bones["forearm.R"]]
    pbone.rigforge_type = ""
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Arm.L (IK)")
    pbone = obj.pose.bones[bones["forearm.L"]]
    pbone.rigforge_type = ""
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Arm.R (IK)")
    pbone = obj.pose.bones[bones["r_hoof.R"]]
    pbone.rigforge_type = ""
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Leg.L (IK)")
    pbone = obj.pose.bones[bones["r_hoof.L"]]
    pbone.rigforge_type = ""
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Leg.R (IK)")
    pbone = obj.pose.bones[bones["neck.003"]]
    pbone.rigforge_type = ""
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Spine")
    pbone = obj.pose.bones[bones["mane_base.03"]]
    pbone.rigforge_type = "limbs.super_finger"
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Hair")
    try:
        pbone.rigforge_parameters.copy_rotation_axes = (True, False, True)
    except AttributeError:
        pass
    try:
        pbone.rigforge_parameters.primary_rotation_axis = "Z"
    except AttributeError:
        pass
    try:
        pbone.rigforge_parameters.tweak_layers_extra = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones["mane_top.04"]]
    pbone.rigforge_type = ""
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Hair")
    pbone = obj.pose.bones[bones["forefoot.R"]]
    pbone.rigforge_type = ""
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Arm.L (IK)")
    pbone = obj.pose.bones[bones["forefoot.L"]]
    pbone.rigforge_type = ""
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Arm.R (IK)")
    pbone = obj.pose.bones[bones["neck.004"]]
    pbone.rigforge_type = ""
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Spine")
    pbone = obj.pose.bones[bones["mane_base.02"]]
    pbone.rigforge_type = "limbs.super_finger"
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Hair")
    try:
        pbone.rigforge_parameters.copy_rotation_axes = (True, False, True)
    except AttributeError:
        pass
    try:
        pbone.rigforge_parameters.primary_rotation_axis = "Z"
    except AttributeError:
        pass
    try:
        pbone.rigforge_parameters.tweak_layers_extra = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones["mane_top.03"]]
    pbone.rigforge_type = ""
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Hair")
    pbone = obj.pose.bones[bones["f_toe.R"]]
    pbone.rigforge_type = ""
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Arm.L (IK)")
    pbone = obj.pose.bones[bones["f_toe.L"]]
    pbone.rigforge_type = ""
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Arm.R (IK)")
    pbone = obj.pose.bones[bones["head"]]
    pbone.rigforge_type = ""
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Spine")
    pbone = obj.pose.bones[bones["mane_base.01"]]
    pbone.rigforge_type = "limbs.super_finger"
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Hair")
    try:
        pbone.rigforge_parameters.copy_rotation_axes = (True, False, True)
    except AttributeError:
        pass
    try:
        pbone.rigforge_parameters.primary_rotation_axis = "Z"
    except AttributeError:
        pass
    try:
        pbone.rigforge_parameters.tweak_layers_extra = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones["mane_base.06"]]
    pbone.rigforge_type = "limbs.super_finger"
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Hair")
    try:
        pbone.rigforge_parameters.copy_rotation_axes = (True, False, True)
    except AttributeError:
        pass
    try:
        pbone.rigforge_parameters.primary_rotation_axis = "Z"
    except AttributeError:
        pass
    try:
        pbone.rigforge_parameters.tweak_layers_extra = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones["mane_top.02"]]
    pbone.rigforge_type = ""
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Hair")
    pbone = obj.pose.bones[bones["f_hoof.R"]]
    pbone.rigforge_type = ""
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Arm.L (IK)")
    pbone = obj.pose.bones[bones["f_hoof.L"]]
    pbone.rigforge_type = ""
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Arm.R (IK)")
    pbone = obj.pose.bones[bones["skull"]]
    pbone.rigforge_type = "basic.super_copy"
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Spine")
    try:
        pbone.rigforge_parameters.make_widget = False
    except AttributeError:
        pass
    try:
        pbone.rigforge_parameters.make_control = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones["ear.R"]]
    pbone.rigforge_type = "limbs.simple_tentacle"
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Face")
    try:
        pbone.rigforge_parameters.copy_rotation_axes = (True, False, True)
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigforge_parameters, "tweak", "Face (Primary)")
    pbone = obj.pose.bones[bones["ear.L"]]
    pbone.rigforge_type = "limbs.simple_tentacle"
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Face")
    try:
        pbone.rigforge_parameters.copy_rotation_axes = (True, False, True)
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigforge_parameters, "tweak", "Face (Primary)")
    pbone = obj.pose.bones[bones["jaw"]]
    pbone.rigforge_type = "limbs.simple_tentacle"
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Face")
    try:
        pbone.rigforge_parameters.make_widget = False
    except AttributeError:
        pass
    try:
        pbone.rigforge_parameters.make_control = False
    except AttributeError:
        pass
    try:
        pbone.rigforge_parameters.copy_rotation_axes = (False, False, False)
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigforge_parameters, "tweak", "Face (Primary)")
    pbone = obj.pose.bones[bones["eye.R"]]
    pbone.rigforge_type = "basic.super_copy"
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Face")
    pbone = obj.pose.bones[bones["nose.R"]]
    pbone.rigforge_type = "basic.super_copy"
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Face")
    pbone = obj.pose.bones[bones["eye.L"]]
    pbone.rigforge_type = "basic.super_copy"
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Face")
    pbone = obj.pose.bones[bones["nose.L"]]
    pbone.rigforge_type = "basic.super_copy"
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Face")
    pbone = obj.pose.bones[bones["mane_top.01"]]
    pbone.rigforge_type = ""
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Hair")
    pbone = obj.pose.bones[bones["mane_top.06"]]
    pbone.rigforge_type = ""
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Hair")
    pbone = obj.pose.bones[bones["skull.R"]]
    pbone.rigforge_type = "basic.super_copy"
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Spine")
    try:
        pbone.rigforge_parameters.make_widget = False
    except AttributeError:
        pass
    try:
        pbone.rigforge_parameters.make_control = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones["skull.L"]]
    pbone.rigforge_type = "basic.super_copy"
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Spine")
    try:
        pbone.rigforge_parameters.make_widget = False
    except AttributeError:
        pass
    try:
        pbone.rigforge_parameters.make_control = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones["ear.R.001"]]
    pbone.rigforge_type = ""
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Face")
    pbone = obj.pose.bones[bones["ear.L.001"]]
    pbone.rigforge_type = ""
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Face")
    pbone = obj.pose.bones[bones["jaw.001"]]
    pbone.rigforge_type = ""
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = "QUATERNION"
    assign_bone_collections(pbone, "Face")

    bpy.ops.object.mode_set(mode="EDIT")
    for bone in arm.edit_bones:
        bone.select = False
        bone.select_head = False
        bone.select_tail = False
    for b in bones:
        bone = arm.edit_bones[bones[b]]
        bone.select = True
        bone.select_head = True
        bone.select_tail = True
        bone.bbone_x = bone.bbone_z = bone.length * 0.05
        arm.edit_bones.active = bone

    arm.collections.active_index = 0

    return bones


if __name__ == "__main__":
    create(bpy.context.active_object)
