# SPDX-License-Identifier: GPL-2.0-or-later
"""Build the HLL metarig presets from stock metarigs.

Headless (from the repo root):
    BLENDER_USER_SCRIPTS=/tmp/rf_scripts \
      /Applications/Blender.app/Contents/MacOS/Blender \
      --background --factory-startup \
      --python tools/make_hll_presets.py -- .

Writes rigforge/metarigs/hll_hero.py and hll_stalker.py (generated
modules — do not hand-edit; tune the constants below and re-run).

Method: add the stock metarig, apply rigid/square-preserving bone
transforms measured from HLL subjects (Andras hero mesh, stalker
blockout), then encode with rigforge.utils.write_metarig.
"""

import math
import os
import sys

import bpy
from mathutils import Matrix, Vector

# Landmarks measured from HLL sources (Blender units, metarig space).
HERO_HEIGHT = 1.14  # Andras_Body_0 bounds z_max
HERO_ARM_DROP_DEG = 45.0  # stock T-pose -> relaxed A-pose
HERO_ARM_STRETCH = 1.15  # Andras arms are long vs stock
HERO_SHOULDER_DROP = 0.06  # stock shoulders sit ~6cm high after scaling

STALKER_SCALE = 0.75  # horse legs ~1.4 -> stalker legs 1.0
STALKER_LEG_X = 0.30  # stalker legs at |x| = 0.3
STALKER_LEG_Y = 0.55  # stalker legs at |y| = 0.55


def descendants(edit_bones, root_name):
    """Root edit-bone name + all descendants, via parent links."""
    children = {}
    for b in edit_bones:
        if b.parent:
            children.setdefault(b.parent.name, []).append(b.name)
    out, stack = [], [root_name]
    while stack:
        name = stack.pop()
        out.append(name)
        stack.extend(children.get(name, []))
    return out


def apply(edit_bones, names, matrix):
    for name in names:
        edit_bones[name].transform(matrix)


def about(pivot, linear):
    """Wrap a 4x4 linear part to act about a pivot point."""
    return Matrix.Translation(pivot) @ linear @ Matrix.Translation(-pivot)


def add_metarig(op_name):
    bpy.ops.object.mode_set(mode="OBJECT")
    bpy.ops.object.select_all(action="SELECT")
    bpy.ops.object.delete(use_global=False)
    getattr(bpy.ops.object, op_name)()
    obj = bpy.context.view_layer.objects.active
    bpy.ops.object.mode_set(mode="EDIT")
    # Disconnect everything while transforming: EditBone.transform()
    # drags connected heads/tails along, which double-applies matrices
    # down a chain. Connections are restored before encoding.
    for b in obj.data.edit_bones:
        b.use_connect = False
    return obj


def reconnect_from(obj, ref_op_name):
    """Restore use_connect flags from a fresh stock metarig of the same type."""
    bpy.ops.object.mode_set(mode="OBJECT")
    getattr(bpy.ops.object, ref_op_name)()
    ref = bpy.context.view_layer.objects.active
    flags = {b.name: b.use_connect for b in ref.data.bones}
    bpy.ops.object.mode_set(mode="OBJECT")
    bpy.ops.object.select_all(action="DESELECT")
    ref.select_set(True)
    bpy.ops.object.delete(use_global=False)
    bpy.context.view_layer.objects.active = obj
    bpy.ops.object.mode_set(mode="EDIT")
    for b in obj.data.edit_bones:
        want = flags[b.name]
        # Only reconnect where the joint is still closed; the head-lift
        # and stance shifts intentionally open some joints.
        if want and b.parent:
            want = (b.head - b.parent.tail).length < 1e-4
        b.use_connect = want
    return obj


def encode(obj, base_name, description):
    from rigforge.utils.rig import write_metarig

    code = write_metarig(
        obj, layers=True, func_name="create", groups=True, widgets=True
    )
    base_path = os.path.join(
        os.path.dirname(rigforge_file()), "metarigs", base_name + ".py"
    )
    with open(base_path, encoding="utf-8") as f:
        header = "".join([next(f) for _ in range(3)])
    doc = (
        header
        + "# HLL preset, generated by tools/make_hll_presets.py from the\n"
        + f"# '{base_name}' stock metarig — do not hand-edit.\n"
        + f"# {description}\n\n"
    )
    return doc + code + "\n"


def rigforge_file():
    import rigforge

    return rigforge.__file__


def build_hero():
    """Stylized biped for Andras-like heroes: 1.14m, relaxed A-pose arms."""
    obj = add_metarig("rigforge_human_metarig_add")
    bones = obj.data.edit_bones

    stock_top = max(max(b.head.z, b.tail.z) for b in bones)
    apply(bones, [b.name for b in bones], Matrix.Scale(HERO_HEIGHT / stock_top, 4))

    for side in ("L", "R"):
        shoulder = descendants(bones, f"shoulder.{side}")
        apply(
            bones, shoulder, Matrix.Translation(Vector((0.0, 0.0, -HERO_SHOULDER_DROP)))
        )
        arm = descendants(bones, f"upper_arm.{side}")
        pivot = bones[f"upper_arm.{side}"].head.copy()
        angle = math.radians(HERO_ARM_DROP_DEG) * (1.0 if side == "L" else -1.0)
        apply(
            bones,
            arm,
            about(
                pivot,
                Matrix.Scale(HERO_ARM_STRETCH, 4) @ Matrix.Rotation(angle, 4, "Y"),
            ),
        )

    hand = bones["hand.L"]
    print(
        f"hero: hand.L tail={[round(v, 3) for v in hand.tail]} "
        f"(mesh hands ~ (±0.26, z 0.45))"
    )
    return reconnect_from(obj, "rigforge_human_metarig_add")


def build_stalker():
    """Quadruped for stalker-like creatures: 1m legs, +Y facing, high head.

    Horse base: its upright neck fits the stalker's rearing neck without
    chain surgery (the head rig requires a connected chain, so the head
    and neck stay exactly as authored, rigidly transformed).
    """
    from rigforge.utils.naming import mirror_name

    obj = add_metarig("rigforge_horse_metarig_add")
    bones = obj.data.edit_bones

    apply(bones, [b.name for b in bones], Matrix.Scale(STALKER_SCALE, 4))
    # Horse faces -Y; HLL creature meshes face +Y. Rigid half-turn, then
    # swap .L/.R labels back so sides stay truthful.
    apply(bones, [b.name for b in bones], Matrix.Rotation(math.pi, 4, "Z"))

    # Widen the stance to the blockout. Limb rigs (unlike the head rig)
    # tolerate disjoint roots, so rigid subtree shifts are safe.
    for root, want_y in (
        ("upper_arm.L", STALKER_LEG_Y),
        ("upper_arm.R", STALKER_LEG_Y),
        ("thigh.L", -STALKER_LEG_Y),
        ("thigh.R", -STALKER_LEG_Y),
    ):
        head = bones[root].head
        dx = math.copysign(STALKER_LEG_X - abs(head.x), head.x or 1.0)
        apply(
            bones,
            descendants(bones, root),
            Matrix.Translation(Vector((dx, want_y - head.y, 0.0))),
        )

    # Two-pass .L/.R swap (mirrored names may collide mid-pass).
    for b in bones:
        b.name = "TMP_" + mirror_name(b.name)
    for b in bones:
        assert b.name.startswith("TMP_")
        b.name = b.name[len("TMP_") :]
    for coll in obj.data.collections_all:
        mirrored = mirror_name(coll.name)
        if mirrored != coll.name:
            coll.name = "TMP_" + mirrored
    for coll in obj.data.collections_all:
        if coll.name.startswith("TMP_"):
            coll.name = coll.name[len("TMP_") :]

    print(
        f"stalker: upper_arm.L head={[round(v, 3) for v in bones['upper_arm.L'].head]} "
        f"skull head={[round(v, 3) for v in bones['skull'].head]}"
    )
    return reconnect_from(obj, "rigforge_horse_metarig_add")


def main():
    bpy.ops.preferences.addon_enable(module="rigforge")
    import rigforge

    print("rigforge:", rigforge.__file__)

    repo = sys.argv[sys.argv.index("--") + 1]
    out_dir = os.path.join(repo, "rigforge", "metarigs")

    hero = build_hero()
    hero_code = encode(
        hero, "human", "Stylized biped starting point (Andras-scale hero)."
    )
    with open(os.path.join(out_dir, "hll_hero.py"), "w", encoding="utf-8") as f:
        f.write(hero_code)

    stalker = build_stalker()
    stalker_code = encode(
        stalker, "Animals/horse", "Quadruped starting point (stalker-scale creature)."
    )
    with open(os.path.join(out_dir, "hll_stalker.py"), "w", encoding="utf-8") as f:
        f.write(stalker_code)

    print(
        "wrote hll_hero.py (%d bytes), hll_stalker.py (%d bytes)"
        % (len(hero_code), len(stalker_code))
    )


if __name__ == "__main__":
    main()
